# tests/load/locustfile.py
"""
Load testing with Locust.

Run:
    locust -f tests/load/locustfile.py --host http://localhost:8000

Web UI: http://localhost:8089
Headless: locust -f tests/load/locustfile.py --host http://localhost:8000 --users 100 --spawn-rate 10 -t 5m --headless
"""
import json
from locust import HttpUser, task, between, tag


class AuthMixin:
    """Get auth token once per user lifecycle."""

    _token: str = ""

    def get_headers(self):
        if not self._token:
            resp = self.client.post("/token", data={
                "username": "admin",
                "password": "admin",  # Use test password
            })
            if resp.status_code == 200:
                self._token = resp.json()["access_token"]
        return {"Authorization": f"Bearer {self._token}"}


class ViewerUser(HttpUser, AuthMixin):
    """Simulates a viewer: reads metrics, alerts, incidents."""
    weight = 7  # 70% of traffic
    wait_time = between(1, 5)

    def on_start(self):
        self.get_headers()

    @tag("read")
    @task(5)
    def list_metrics(self):
        self.client.get("/api/v1/metrics/", headers=self.get_headers())

    @tag("read")
    @task(5)
    def list_alerts(self):
        self.client.get("/api/v1/alerts/?limit=50", headers=self.get_headers())

    @tag("read")
    @task(3)
    def list_incidents(self):
        self.client.get("/api/v1/incidents/?limit=20", headers=self.get_headers())

    @tag("read")
    @task(2)
    def list_rules(self):
        self.client.get("/api/v1/rules/", headers=self.get_headers())

    @tag("read")
    @task(1)
    def health_check(self):
        self.client.get("/health")

    @tag("read")
    @task(1)
    def list_dimensions(self):
        self.client.get("/api/v1/dimensions/", headers=self.get_headers())


class OperatorUser(HttpUser, AuthMixin):
    """Simulates an operator: reads + mutates incidents."""
    weight = 2  # 20% of traffic
    wait_time = between(2, 8)

    def on_start(self):
        self.get_headers()

    @tag("read")
    @task(4)
    def list_incidents(self):
        self.client.get("/api/v1/incidents/", headers=self.get_headers())

    @tag("read")
    @task(3)
    def list_alerts(self):
        self.client.get("/api/v1/alerts/", headers=self.get_headers())

    @tag("write")
    @task(1)
    def create_incident(self):
        self.client.post(
            "/api/v1/incidents/",
            json={
                "alert_message": "Load test incident",
                "metric": "cpu_usage",
                "region": "RU-MOW",
                "priority": "low",
                "description": "Generated by locust load test",
            },
            headers=self.get_headers(),
        )

    @tag("read")
    @task(2)
    def list_sla_policies(self):
        self.client.get("/api/v1/incidents/sla/policies", headers=self.get_headers())


class AdminUser(HttpUser, AuthMixin):
    """Simulates an admin: heavy management operations."""
    weight = 1  # 10% of traffic
    wait_time = between(5, 15)

    def on_start(self):
        self.get_headers()

    @tag("admin")
    @task(3)
    def list_users(self):
        self.client.get("/api/v1/admin/users", headers=self.get_headers())

    @tag("admin")
    @task(2)
    def list_tenants(self):
        self.client.get("/api/v1/admin/tenants", headers=self.get_headers())

    @tag("admin")
    @task(1)
    def list_audit_logs(self):
        self.client.get("/api/v1/audit/logs?limit=50", headers=self.get_headers())

    @tag("read")
    @task(2)
    def list_ml_configs(self):
        self.client.get("/api/v1/ml/configs/", headers=self.get_headers())
