// ISO 3166-2:RU subject codes → the exact region `name` used in public/russia.geojson.
// Incidents/metrics may carry either a code (e.g. "RU-MOW") or already a full name;
// resolveRegionName() normalises both to a geojson name so they can be drawn on the map.
// Values here are copied verbatim from russia.geojson (note the em-dashes "—").
export const RU_CODE_TO_NAME: Record<string, string> = {
  'RU-AD': 'Адыгея',
  'RU-AL': 'Республика Алтай',
  'RU-ALT': 'Алтайский край',
  'RU-AMU': 'Амурская область',
  'RU-ARK': 'Архангельская область',
  'RU-AST': 'Астраханская область',
  'RU-BA': 'Башкортостан',
  'RU-BEL': 'Белгородская область',
  'RU-BRY': 'Брянская область',
  'RU-BU': 'Республика Бурятия',
  'RU-CE': 'Чечня',
  'RU-CHE': 'Челябинская область',
  'RU-CHU': 'Чукотский автономный округ',
  'RU-CU': 'Чувашия',
  'RU-DA': 'Дагестан',
  'RU-IN': 'Ингушетия',
  'RU-IRK': 'Иркутская область',
  'RU-IVA': 'Ивановская область',
  'RU-KAM': 'Камчатский край',
  'RU-KB': 'Кабардино-Балкария',
  'RU-KC': 'Карачаево-Черкесия',
  'RU-KDA': 'Краснодарский край',
  'RU-KEM': 'Кемеровская область',
  'RU-KGD': 'Калининградская область',
  'RU-KGN': 'Курганская область',
  'RU-KHA': 'Хабаровский край',
  'RU-KHM': 'Ханты-Мансийский автономный округ — Югра',
  'RU-KIR': 'Кировская область',
  'RU-KK': 'Республика Хакасия',
  'RU-KL': 'Калмыкия',
  'RU-KLU': 'Калужская область',
  'RU-KO': 'Республика Коми',
  'RU-KOS': 'Костромская область',
  'RU-KR': 'Карелия',
  'RU-KRS': 'Курская область',
  'RU-KYA': 'Красноярский край',
  'RU-LEN': 'Ленинградская область',
  'RU-LIP': 'Липецкая область',
  'RU-MAG': 'Магаданская область',
  'RU-ME': 'Марий Эл',
  'RU-MO': 'Мордовия',
  'RU-MOW': 'Москва',
  'RU-MOS': 'Московская область',
  'RU-MUR': 'Мурманская область',
  'RU-NEN': 'Ненецкий автономный округ',
  'RU-NGR': 'Новгородская область',
  'RU-NIZ': 'Нижегородская область',
  'RU-NVS': 'Новосибирская область',
  'RU-OMS': 'Омская область',
  'RU-ORE': 'Оренбургская область',
  'RU-ORL': 'Орловская область',
  'RU-PER': 'Пермский край',
  'RU-PNZ': 'Пензенская область',
  'RU-PRI': 'Приморский край',
  'RU-PSK': 'Псковская область',
  'RU-ROS': 'Ростовская область',
  'RU-RYA': 'Рязанская область',
  'RU-SA': 'Республика Саха (Якутия)',
  'RU-SAK': 'Сахалинская область',
  'RU-SAM': 'Самарская область',
  'RU-SAR': 'Саратовская область',
  'RU-SE': 'Северная Осетия — Алания',
  'RU-SMO': 'Смоленская область',
  'RU-SPE': 'Санкт-Петербург',
  'RU-STA': 'Ставропольский край',
  'RU-SVE': 'Свердловская область',
  'RU-TA': 'Татарстан',
  'RU-TAM': 'Тамбовская область',
  'RU-TOM': 'Томская область',
  'RU-TUL': 'Тульская область',
  'RU-TVE': 'Тверская область',
  'RU-TY': 'Республика Тыва',
  'RU-TYU': 'Тюменская область',
  'RU-UD': 'Удмуртия',
  'RU-ULY': 'Ульяновская область',
  'RU-VGG': 'Волгоградская область',
  'RU-VLA': 'Владимирская область',
  'RU-VLG': 'Вологодская область',
  'RU-VOR': 'Воронежская область',
  'RU-YAN': 'Ямало-Ненецкий автономный округ',
  'RU-YAR': 'Ярославская область',
  'RU-YEV': 'Еврейская автономная область',
  'RU-ZAB': 'Забайкальский край',
};

// Normalise a region value (code or full name) to a geojson `name`, or null if it is
// not a mappable geographic region (e.g. "all", "localhost", an unknown code).
export function resolveRegionName(region: string | null | undefined): string | null {
  if (!region) return null;
  if (RU_CODE_TO_NAME[region]) return RU_CODE_TO_NAME[region];
  // Already a full geojson name (or close enough to match by name on the map).
  if (Object.values(RU_CODE_TO_NAME).includes(region)) return region;
  return null;
}
